# Generated by Django 2.2.2 on 2019-06-12 20:47
import uuid

from django.db import migrations


def populate_api_tokens(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("emails", "Profile")
    for user in User.objects.all():
        profiles = Profile.objects.filter(user=user)
        if not profiles:
            Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_profile"),
    ]

    operations = [
        migrations.RunPython(populate_api_tokens),
    ]
