# Generated by Django 2.2.9 on 2020-01-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_auto_20190612_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
