# Generated by Django 2.2.10 on 2020-03-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20200101_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
