# Generated by Django 2.2.10 on 2020-03-10 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_delete_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayaddress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="description",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="num_blocked",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="num_forwarded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="num_spam",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
