# Generated by Django 2.2.13 on 2021-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_domainaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainaddress',
            name='address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
