# Generated by Django 2.2.13 on 2021-03-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_auto_20210317_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainaddress',
            name='last_emailed_at',
        ),
    ]
