# Generated by Django 2.2.24 on 2021-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_remove_unique_from_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayaddress',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RELAY_FIREFOX_DOMAIN'), (2, 'MOZMAIL_DOMAIN')], default=1),
        ),
    ]
