# Generated by Django 2.2.24 on 2021-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_remove_unique_from_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayaddress',
            name='num_click_trackers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relayaddress',
            name='num_open_trackers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
