# Generated by Django 2.2.24 on 2021-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_add_num_click_and_open_trackers'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainaddress',
            name='num_click_trackers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domainaddress',
            name='num_open_trackers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
