# Generated by Django 2.2.24 on 2021-08-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_relayaddress_domain'),
        ('emails', '0018_reply_squashed_0022_auto_20210817_0327'),
    ]

    operations = [
    ]
