# Generated by Django 2.2.24 on 2021-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0020_reply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='lookup',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
