# Generated by Django 2.2.24 on 2021-09-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0021_auto_20210920_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainaddress',
            name='domain',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RELAY_FIREFOX_DOMAIN'), (2, 'MOZMAIL_DOMAIN')], default=2),
        ),
    ]
