# Generated by Django 2.2.24 on 2021-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0022_domainaddress_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="server_storage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="generated_for",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
