# Generated by Django 2.2.24 on 2021-11-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0030_check_and_fix_any_duplicate_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
