# Generated by Django 2.2.24 on 2021-11-05 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0031_profile_onboarding_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbuseMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_recorded",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "last_recorded",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "num_address_created_per_day",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("num_replies_per_day", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "first_recorded")},
            },
        ),
    ]
