# Generated by Django 2.2.24 on 2021-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0032_abusemetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_account_flagged",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
