# Generated by Django 2.2.24 on 2021-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0034_relay_address_default_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_subscribed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
