# Generated by Django 2.2.24 on 2021-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0034_relay_address_default_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedaddress',
            name='num_replied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domainaddress',
            name='num_replied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relayaddress',
            name='num_replied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
