# Generated by Django 2.2.24 on 2021-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0035_add_num_replied_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_email_replied_in_deleted_address',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
