# Generated by Django 2.2.24 on 2022-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0037_reply_add_index_on_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_block_spam',
            field=models.BooleanField(default=False),
        ),
    ]
