# Generated by Django 2.2.26 on 2022-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0039_profile_auto_block_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainaddress",
            name="block_list_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="block_list_emails",
            field=models.BooleanField(default=False),
        ),
    ]
