# Generated by Django 2.2.27 on 2022-04-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0040_add_block_list_emails_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayaddress',
            name='used_on',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
