# Generated by Django 3.2.13 on 2022-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0041_relayaddress_used_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainaddress",
            name="used_on",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
