# Generated by Django 3.2.13 on 2022-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0045_deletedaddress_num_replied"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="remove_level_one_email_trackers",
            field=models.BooleanField(default=False),
        ),
    ]
