# Generated by Django 3.2.13 on 2022-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0046_profile_remove_level_one_email_trackers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="remove_level_one_email_trackers",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
