# Generated by Django 3.2.13 on 2022-06-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0047_alter_profile_remove_level_one_email_trackers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="server_storage",
            field=models.BooleanField(default=True),
        ),
    ]
