# Generated by Django 3.2.13 on 2022-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0048_alter_profile_server_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainaddress",
            name="num_level_one_trackers_blocked",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="num_level_one_trackers_blocked_in_deleted_address",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="relayaddress",
            name="num_level_one_trackers_blocked",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
