# Generated by Django 3.2.14 on 2022-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0049_add_num_level_one_trackers_blocked_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_phone_log',
            field=models.BooleanField(default=True),
        ),
    ]
