# Generated by Django 3.2.15 on 2022-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "emails",
            "0051_add_email_size_per_day_and_num_email_forwarded_per_day_fields",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_phone_subscription_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_subscribed_phone",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
