# Generated by Django 3.2.16 on 2022-12-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0053_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="forwarded_first_reply",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
