# Generated by Django 3.2.16 on 2023-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0054_profile_forwarded_first_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_phone_subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_phone_subscription_reset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_phone_subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
