# Generated by Django 3.2.19 on 2023-10-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0057_profile_sent_welcome_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarding_free_state",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
