# Generated by Django 4.2.10 on 2024-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emails",
            "0060_add_num_deleted_relay_addresses_and_num_deleted_domain_addresses_to_profile",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="locale",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
