# Generated by Django 4.2.13 on 2024-06-07 22:08
# Move Profile and RegisteredSubdomain to privaterelay app
# Other half is
# privaterelay/migrations/0010_move_profile_and_registered_subdomain_models.py
# See https://davit.hashnode.dev/django-move-model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0061_relayaddress_idx_ra_created_by_addon"),
    ]

    state_operations = [
        migrations.RemoveField(model_name="profile", name="user"),
        migrations.DeleteModel(name="RegisteredSubdomain"),
        migrations.DeleteModel(name="Profile"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
