# Generated by Django 4.2.13 on 2024-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0062_move_profile_and_registered_subdomain_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domainaddress",
            options={"verbose_name_plural": "domain addresses"},
        ),
        migrations.AlterModelOptions(
            name="relayaddress",
            options={"verbose_name_plural": "relay addresses"},
        ),
    ]
