# Generated by Django 2.2.9 on 2019-12-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="initiating_real_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
