# Generated by Django 2.2.9 on 2019-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0004_auto_20191223_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
