# Generated by Django 3.2.13 on 2022-05-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0008_alter_realphone_verified_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="realphone",
            name="verification_sent_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
