# Generated by Django 3.2.13 on 2022-07-01 19:08

from django.db import migrations, models
import phones.models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0012_relaynumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaynumber",
            name="vcard_lookup_key",
            field=models.CharField(
                default=phones.models.vcard_lookup_key_default,
                max_length=6,
                unique=True,
            ),
        ),
    ]
