# Generated by Django 3.2.13 on 2022-07-08 19:40

from django.db import migrations, models
import phones.models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0014_delete_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realphone",
            name="verification_sent_date",
            field=models.DateTimeField(
                blank=True,
                default=phones.models.verification_sent_date_default,
                null=True,
            ),
        ),
    ]
