# Generated by Django 3.2.14 on 2022-08-07 21:30

import django.db.models.deletion
from django.db import migrations, models

import phones.models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0017_relaynumber_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inbound_number", models.CharField(max_length=15)),
                (
                    "last_inbound_date",
                    models.DateTimeField(
                        default=phones.models.last_inbound_date_default
                    ),
                ),
                ("num_calls", models.PositiveIntegerField(default=0)),
                ("num_calls_blocked", models.PositiveIntegerField(default=0)),
                ("num_texts", models.PositiveIntegerField(default=0)),
                ("num_texts_blocked", models.PositiveIntegerField(default=0)),
                ("blocked", models.BooleanField(default=False)),
                (
                    "relay_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phones.relaynumber",
                    ),
                ),
            ],
        ),
    ]
