# Generated by Django 3.2.14 on 2022-08-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0018_inboundcontact"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inboundcontact",
            index=models.Index(
                fields=["relay_number", "inbound_number"],
                name="phones_inbo_relay_n_eaf332_idx",
            ),
        ),
    ]
