# Generated by Django 3.2.15 on 2022-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0020_inboundcontact_last_inbound_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaynumber",
            name="remaining_minutes",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name="relaynumber",
            name="remaining_texts",
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
    ]
