# Generated by Django 3.2.15 on 2022-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0021_auto_20220830_add_remaining_stats_to_relaynumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaynumber",
            name="calls_blocked",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="relaynumber",
            name="calls_forwarded",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="relaynumber",
            name="texts_blocked",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="relaynumber",
            name="texts_forwarded",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
