# Generated by Django 3.2.15 on 2022-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0024_add_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relaynumber",
            name="number",
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
