# Generated by Django 3.2.16 on 2022-11-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0025_alter_relaynumber_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundcontact",
            name="last_call_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="inboundcontact",
            name="last_text_date",
            field=models.DateTimeField(null=True),
        ),
    ]
