# Generated by Django 3.2.16 on 2023-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0026_inboundcontact_add_last_call_and_text_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaynumber",
            name="vendor",
            field=models.CharField(default="twilio", max_length=15),
        ),
    ]
