# Generated by Django 4.2.9 on 2024-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0029_relaynumber_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relaynumber",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
