# Generated by Django 5.2.14 on 2026-06-03 20:47

import logging

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger("eventsinfo")


def deduplicate_relay_numbers(apps, schema_editor):
    """
    Remove duplicate RelayNumber rows so the unique constraint can be applied.

    If a user has multiple RelayNumber rows (from the race condition in
    MPP-4682), keep the one with the most forwarded calls and texts. Delete
    the rest. Log each deleted number so Twilio numbers can be released
    manually.
    """
    RelayNumber = apps.get_model("phones", "RelayNumber")
    db_alias = schema_editor.connection.alias

    # Find users with more than one RelayNumber
    from django.db.models import Count

    duplicates = (
        RelayNumber.objects.using(db_alias)
        .values("user_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for entry in duplicates:
        user_id = entry["user_id"]
        numbers = list(
            RelayNumber.objects.using(db_alias)
            .filter(user_id=user_id)
            .order_by("-calls_forwarded", "-texts_forwarded", "created_at")
        )
        # Keep the first (most active / earliest created), delete the rest
        keep = numbers[0]
        to_delete = numbers[1:]
        for rn in to_delete:
            logger.warning(
                "MPP-4682: deleting duplicate RelayNumber",
                extra={
                    "user_id": user_id,
                    "deleted_number": rn.number,
                    "deleted_id": rn.id,
                    "kept_number": keep.number,
                    "kept_id": keep.id,
                },
            )
            rn.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0030_alter_relaynumber_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_relay_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="relaynumber",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
