# Type stubs for Django waffle
# https://github.com/django-waffle/django-waffle/blob/v3.0.0/waffle/testutils.py
# Can be removed once type hints ship in the release after v3.0.0

from typing import Generic, TypeVar

from django.test.utils import TestContextDecorator

_T = TypeVar("_T")
_FlagActive = bool | None
_SampleActive = bool | float | None

class _overrider(TestContextDecorator, Generic[_T]):
    name: str
    active: _T

    def __init__(self, name: str, active: _T) -> None: ...
    def get(self) -> None: ...
    def update(self, active: _T) -> None: ...
    def get_value(self) -> _T: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...

class override_switch(_overrider[bool]):
    def update(self, active: bool) -> None: ...
    def get_value(self) -> bool: ...

class override_flag(_overrider[_FlagActive]):
    def update(self, active: _FlagActive) -> None: ...
    def get_value(self) -> _FlagActive: ...

class override_sample(_overrider[_SampleActive]):
    created: bool
    def get(self) -> None: ...
    def update(self, active: _SampleActive) -> None: ...
    def get_value(self) -> _SampleActive: ...
