from _typeshed import Incomplete
from waffle import defaults as defaults

def get_setting(name, default: Incomplete | None = ...): ...
def keyfmt(k, v: Incomplete | None = ...): ...
def get_cache(): ...
