# Generated by Django 2.2.10 on 2020-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Invitations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("date_redeemed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
