# Generated by Django 2.2.13 on 2020-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privaterelay', '0002_add_fxa_uid_to_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitations',
        ),
    ]
