# Generated by Django 3.2.19 on 2023-06-09 18:05

from django.db import migrations


def add_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.get_or_create(
        name="new_from_address",
        defaults={"note": "MPP-1813: Try different reply address"},
    )


def remove_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(name="new_from_address").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("privaterelay", "0004_delete_monitorsubscriber"),
        ("waffle", "0004_update_everyone_nullbooleanfield"),
    ]

    operations = [
        migrations.RunPython(code=remove_flag, reverse_code=add_flag, elidable=True),
    ]
