# Generated by Django 4.2.7 on 2023-11-13 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("privaterelay", "0006_add_email_indexes"),
        ("account", "0002_email_max_length"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE account_emailaddress SET verified=True;",
            reverse_sql="UPDATE account_emailaddress SET verified=False;",
            elidable=True,
        )
    ]
