from .utils import generate_code_challenge as generate_code_challenge
from allauth.socialaccount.providers.base import Provider as Provider

class OAuth2Provider(Provider):
    pkce_enabled_default: bool
    def get_login_url(self, request, **kwargs): ...
    def get_pkce_params(self): ...
    def get_auth_params(self, request, action): ...
    def get_scope(self, request): ...
    def get_default_scope(self): ...
