name: Dependabot update glean-parser generated code
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: write

jobs:
  regen-with-new-glean-parser:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && startsWith( github.head_ref, 'dependabot/pip/glean-parser' ) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'recursive'
          persist-credentials: false
      - name: Checkout pull request
        run: gh pr checkout --recurse-submodules ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run glean-parser to regenerate code
        run: .github/workflows/python/python_job.bash run build_glean
      - name: Commit changed file
        run: |
          git config user.email "<>"
          git config user.name "GitHub Actions - Run new glean-parser"
          git add privaterelay/glean/server_events.py
          has_changes=1
          git commit --message="Re-generate code with glean-parser $GLEAN_VERSION" || has_changes=0
          if (( has_changes == 0 ))
          then
            echo "no changes to push"
            exit 0
          fi
          git push
        env:
          GLEAN_VERSION: ${{steps.dependabot-metadata.outputs.new-version}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
