name: Lint Pending Translations
on:
  push:
    paths:
      - 'frontend/pendingTranslations.ftl'
      - '.github/workflows/lint-pending-strings.yml'
      - 'privaterelay/pending_locales/en/pending.ftl'
    branches: [ '*' ]
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.5.2
        with:
          submodules: 'recursive'
      - name: Set up Python 3
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r privaterelay/locales/.github/requirements.txt
      - name: Lint frontend pending translations
        run: |
          moz-fluent-lint frontend --config privaterelay/locales/.github/linter_config.yml
      - name: Lint backend pending translations
        run: |
          moz-fluent-lint privaterelay/pending_locales --config privaterelay/locales/.github/linter_config.yml
